---
language: clojure
lein: lein2
jdk:
- openjdk6
- openjdk7
env:
  global:
  - secure: ! 'RVlDbSqTHZprcMdnoHNJKIyeQLi3Q1oaGBWZJ7R7GYjsTtiOrp39hxumvHFo

      Mhlt1U9WG0h9FlXE9wR9yLti7aqmhEkUIN4FbMh4EW/FpDB7J+zNjYBNuM0M

      fX1HF5NDmZfUV9h0/NtWxZUhoIUwvzw+IucZ84Awfh+xLpRBOEY='
